// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		// Replace this comment with your code
		int times = Integer.parseInt(args[0]);
		System.out.println(times);
		double rnd;
		int moreThanHalf = 0;
		int lessThanHalf = 0;
		// System.out.println(rnd);
		for (int i = 0; i < times; i++) {
			rnd = Math.random();
			if (rnd > 0.5) {
				moreThanHalf++;
			} else {
				lessThanHalf++;
			}
		}
		System.out.println("> 0.5: " + moreThanHalf + " times");
		System.out.println("<= 0.5: " + lessThanHalf + " times");

		double ratio = 0.0;

		if (lessThanHalf == 0) {
			ratio = 1.0;
		} else {
			ratio = ((double) moreThanHalf / (double) lessThanHalf);
		}
		System.out.println("ratio: " + ratio);
	}
}
